In [2]:
import numpy as np
import cv2
from utils import *
from sklearn.preprocessing import StandardScaler

In [3]:
data = database_to_table("./database/")
data

Currently listed people in database: 
==> adam
==> andreea
==> carla
==> colin
==> dan
==> dennis
==> derek
==> derrick
==> eric
==> graham
==> kate
==> keith
==> nicholas
==> ntjy
==> paul
==> sarah
==> tasos
==> yihang
==> yogesh
==> yongmin
current path ./database/adam. Counter = 0
current path ./database/andreea. Counter = 1
current path ./database/carla. Counter = 2
current path ./database/colin. Counter = 3
current path ./database/dan. Counter = 4
current path ./database/dennis. Counter = 5
current path ./database/derek. Counter = 6
current path ./database/derrick. Counter = 7
current path ./database/eric. Counter = 8
current path ./database/graham. Counter = 9
current path ./database/kate. Counter = 10
current path ./database/keith. Counter = 11
current path ./database/nicholas. Counter = 12
current path ./database/ntjy. Counter = 13
current path ./database/paul. Counter = 14
current path ./database/sarah. Counter = 15
current path ./database/tasos. Counter = 16
current path ./d

array([[178, 184, 181, ..., 200, 139, 165],
       [176, 181, 182, ..., 210, 139, 157],
       [179, 195, 180, ..., 202, 147, 169],
       ...,
       [182, 180, 179, ..., 214, 152, 167],
       [178, 177, 178, ..., 207, 153, 164],
       [188, 161, 113, ..., 210, 157, 165]], dtype=uint8)

In [4]:
#standardised dataset
data_std = StandardScaler().fit_transform(data)

/home/nicholas_sadjoli/.virtualenvs/ee4208_assign_2/local/lib/python2.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [5]:
#calculate mean face
mean = np.mean(data,axis=0)
mean_std = np.mean(data_std,axis=0)
np.savetxt("average_face_test_ii.csv", mean, delimiter=",")
cv2.imwrite("average_face_test_ii.jpg", np.array(np.reshape(mean, (100,100))) )
np.savetxt("average_face_test_ii_std.csv", mean_std, delimiter=",")
cv2.imwrite("average_face_test_ii_std.jpg", np.array(np.reshape(mean_std, (100,100))) )

True

In [6]:
mean_deduct = data - mean
mean_deduct_std = data_std - mean_std
print mean_deduct.shape, mean_deduct.dtype, data.dtype, mean.dtype

(100, 10000) float64 uint8 float64


In [7]:
#default_covariance
cov = mean_deduct.T.dot(mean_deduct)/(mean_deduct.shape[0] - 1)
cov_std = mean_deduct_std.T.dot(mean_deduct_std)/(mean_deduct_std.shape[0] - 1)
print cov
print cov_std
np.shape(cov)

[[2733.05818182 2835.05959596 2852.74666667 ...  875.87979798
  1938.32383838 2318.5640404 ]
 [2835.05959596 3075.07828283 3111.37171717 ...  842.72979798
  1951.27929293 2360.26868687]
 [2852.74666667 3111.37171717 3267.96606061 ...  824.96161616
  2000.12646465 2381.36646465]
 ...
 [ 875.87979798  842.72979798  824.96161616 ... 1461.58333333
  1335.96313131 1467.93333333]
 [1938.32383838 1951.27929293 2000.12646465 ... 1335.96313131
  2199.67787879 2386.02060606]
 [2318.5640404  2360.26868687 2381.36646465 ... 1467.93333333
  2386.02060606 2873.6420202 ]]
[[1.01010101 0.9878124  0.96419484 ... 0.44266286 0.7985225  0.83568601]
 [0.9878124  1.01010101 0.99140213 ... 0.40152563 0.7578384  0.80201378]
 [0.96419484 0.99140213 1.01010101 ... 0.38128348 0.7535359  0.78493905]
 ...
 [0.44266286 0.40152563 0.38128348 ... 1.01010101 0.75260646 0.72350746]
 [0.7985225  0.7578384  0.7535359  ... 0.75260646 1.01010101 0.95861257]
 [0.83568601 0.80201378 0.78493905 ... 0.72350746 0.95861257 1.010

(10000, 10000)

In [8]:
#numpy's covariance
cov_np = np.cov(mean_deduct.T)
cov_np_std = np.cov(mean_deduct_std.T)
print cov_np
print cov_np_std

[[2733.05818182 2835.05959596 2852.74666667 ...  875.87979798
  1938.32383838 2318.5640404 ]
 [2835.05959596 3075.07828283 3111.37171717 ...  842.72979798
  1951.27929293 2360.26868687]
 [2852.74666667 3111.37171717 3267.96606061 ...  824.96161616
  2000.12646465 2381.36646465]
 ...
 [ 875.87979798  842.72979798  824.96161616 ... 1461.58333333
  1335.96313131 1467.93333333]
 [1938.32383838 1951.27929293 2000.12646465 ... 1335.96313131
  2199.67787879 2386.02060606]
 [2318.5640404  2360.26868687 2381.36646465 ... 1467.93333333
  2386.02060606 2873.6420202 ]]
[[1.01010101 0.9878124  0.96419484 ... 0.44266286 0.7985225  0.83568601]
 [0.9878124  1.01010101 0.99140213 ... 0.40152563 0.7578384  0.80201378]
 [0.96419484 0.99140213 1.01010101 ... 0.38128348 0.7535359  0.78493905]
 ...
 [0.44266286 0.40152563 0.38128348 ... 1.01010101 0.75260646 0.72350746]
 [0.7985225  0.7578384  0.7535359  ... 0.75260646 1.01010101 0.95861257]
 [0.83568601 0.80201378 0.78493905 ... 0.72350746 0.95861257 1.010

In [9]:
eig_val, eig_vect = np.linalg.eigh(cov)
#eig_val_std, eig_vect_std = np.linalg.eigh(cov_std)
print np.shape(eig_val), np.shape(eig_vect), #np.shape(eig_val_std), np.shape(eig_vect_std)

(10000,) (10000, 10000)


In [10]:
for i in range(0,10): #(len(eig_vect))
    print i, np.testing.assert_array_almost_equal(1.0, np.linalg.norm(eig_vect[:,i])), np.shape(eig_vect[:,i])#,  np.testing.assert_array_almost_equal(1.0, np.linalg.norm(eig_vect_std[:,i])), np.shape(eig_vect_std[:,i])
print ("Every eigenvector is confirmed to have length of about 1")

0 None (10000,)
1 None (10000,)
2 None (10000,)
3 None (10000,)
4 None (10000,)
5 None (10000,)
6 None (10000,)
7 None (10000,)
8 None (10000,)
9 None (10000,)
Every eigenvector is confirmed to have length of about 1


In [11]:
eigen_pairs = [(np.abs(eig_val[i]), eig_vect[:,i]) for i in range (len(eig_val))]
#eigen_pairs_std = [(np.abs(eig_val_std[i]), eig_vect_std[:,i]) for i in range (len(eig_val_std))]

In [13]:
for k in range(0,10): #(len(eigen_pairs)):
    print eigen_pairs[k][0] #, eigen_pairs_std[k][0]

2.2659326113804198e-09
1.877810454165308e-09
1.4306684690362002e-09
1.363484005370041e-09
1.2343656995197156e-09
1.1515196942646209e-09
1.148748439053333e-09
1.0603942242708938e-09
9.909831320765816e-10
8.332733598900666e-10


In [14]:
#note that you can specify a function as the key so that sorted() can sort based on your specified function. 
#in this case, eigen pair is sorted based on the value of the eigenvalue
eigen_pair_sorted = sorted(eigen_pairs, key=lambda pair:pair[0])
#eigen_pair_sorted_std =  sorted(eigen_pairs_std, key=lambda pair:pair[0])
print eigen_pair_sorted[0], eigen_pair_sorted[9999] #, eigen_pair_sorted_std[0], eigen_pair_sorted_std[9999]

(4.0022245385968177e-16, array([ 0.00000000e+00, -1.11946475e-05, -2.44142408e-04, ...,
       -9.18426515e-03,  3.47050607e-03, -9.53236213e-03])) (6630378.903103545, array([0.01480873, 0.01480757, 0.01563737, ..., 0.005377  , 0.01373792,
       0.01396397]))


In [15]:
eigen_pair_sorted.reverse()
#eigen_pair_sorted_std.reverse()
print eigen_pair_sorted[0], eigen_pair_sorted[9999], #eigen_pair_sorted_std[0], eigen_pair_sorted_std[9999]

(6630378.903103545, array([0.01480873, 0.01480757, 0.01563737, ..., 0.005377  , 0.01373792,
       0.01396397])) (4.0022245385968177e-16, array([ 0.00000000e+00, -1.11946475e-05, -2.44142408e-04, ...,
       -9.18426515e-03,  3.47050607e-03, -9.53236213e-03]))


In [17]:
'''
for count, pair in enumerate(eigen_pair_sorted):
    print count, pair[0], np.testing.assert_array_almost_equal(1.0, np.linalg.norm(eigen_pair_sorted[i][1])), np.shape(eigen_pair_sorted[i][1])
'''

'''
for count, pair in enumerate(eigen_pair_sorted_std):
    print count, pair[0]
'''

'\nfor count, pair in enumerate(eigen_pair_sorted_std):\n    print count, pair[0]\n'

In [18]:
temp = []
temp_std = []
counter = 0
#counter_std = 0
for pair in eigen_pair_sorted:
    if counter == 200:
        break
    temp.append(np.real(pair[1]))
    counter += 1
    
'''    
for pair_std in eigen_pair_sorted_std:
    if counter_std == 125:
        break
    temp_std.append(np.real(pair_std[1]))
    counter_std += 1
'''
    
eig_vect_sorted = np.array(temp).T
print np.shape(eig_vect_sorted)
#eig_vect_sorted_std = np.array(temp_std).T
print eig_vect_sorted, np.shape(eig_vect_sorted), 
#print eig_vect_sorted_std, np.shape(eig_vect_sorted_std)
np.savetxt("eigenvector_nptest.csv", eig_vect_sorted, delimiter=",")
#np.savetxt("eigenvector_nptest_std.csv", eig_vect_sorted_std, delimiter=",")

(10000, 200)
[[ 1.48087265e-02  6.62987771e-03 -3.03563557e-03 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.48075653e-02  7.78966126e-03 -4.14613911e-03 ... -2.77369787e-04
  -3.99705084e-04  3.16160364e-04]
 [ 1.56373682e-02  7.70865998e-03 -4.11064649e-03 ...  9.05292263e-05
  -3.98873993e-04  2.20779750e-04]
 ...
 [ 5.37700189e-03  4.14391704e-04 -2.83421572e-03 ... -4.21523080e-03
   1.00990971e-02  2.89618049e-03]
 [ 1.37379245e-02  3.55760177e-03 -3.33114492e-03 ... -5.36194210e-03
   7.01798671e-03  2.37175941e-02]
 [ 1.39639725e-02  6.15123537e-03 -3.11629498e-03 ... -2.48551072e-02
  -9.45842248e-03 -1.47303850e-02]] (10000, 200)


In [19]:
eig_vect_scaled = np.copy(eig_vect_sorted) * 255
np.savetxt("eigenvector_nptest_scaled.csv", eig_vect_scaled, delimiter=",")
eig_vect_normalized = np.copy(eig_vect_sorted)
for i in range(0,10000):
    eig_vect_normalized[i] = eig_vect_normalized[i] / np.linalg.norm(eig_vect_normalized[i])
np.savetxt("eigenvector_nptest_normalized.csv", eig_vect_normalized, delimiter=",")
eig_vect_normalized_scaled = np.copy(eig_vect_normalized) * 255
np.savetxt("eigenvector_nptest_normalized_scaled.csv", eig_vect_normalized_scaled, delimiter=",")

In [20]:
for j in range(0,10):
    cv2.imwrite("eigenfaces_test_"+str(j)+".jpg", np.reshape(eig_vect_sorted[:,j], (100,100)) )
    #cv2.imwrite("eigenfaces_test_std_"+str(j)+".jpg", np.reshape(eig_vect_sorted_std[:,j], (100,100)) )
    cv2.imwrite("eigenfaces_test_scaled_"+str(j)+".jpg", np.reshape(eig_vect_scaled[:,j],(100,100)) ) 
    cv2.imwrite("eigenfaces_test_normalized_"+str(j)+".jpg", np.reshape(eig_vect_normalized[:,j], (100,100)) )
    cv2.imwrite("eigenfaces_test_normalized_scaled"+str(j)+".jpg", np.reshape(eig_vect_normalized_scaled[:,j], (100,100)) )

In [21]:
reduced = mean_deduct.dot(eig_vect_sorted)
#reduced_std = mean_deduct_std.dot(eig_vect_sorted_std)
reduced_scaled = mean_deduct.dot(eig_vect_scaled)
reduced_normalized = mean_deduct.dot(eig_vect_normalized)
reduced_normalized_scaled = mean_deduct.dot(eig_vect_normalized_scaled)
print np.shape(reduced)
np.savetxt("reduced.csv", reduced, delimiter=",")
#np.savetxt("reduced_test_plotlyguide_std.csv", reduced_std, delimiter=",")
np.savetxt("reduced_scaled.csv", reduced_scaled, delimiter=",")
np.savetxt("reduced_norm.csv", reduced_normalized, delimiter=",")
np.savetxt("reduced_norm_scaled.csv", reduced_normalized_scaled, delimiter=",")

(100, 200)
