In [2]:
import numpy as np
import cv2
from utils import *
from sklearn.preprocessing import StandardScaler

In [3]:
data = database_to_table("./database/")
data

Currently listed people in database: 
==> adam
==> andreea
==> carla
==> colin
==> dan
==> dennis
==> derek
==> derrick_nospec
==> eric
==> graham
==> heather
==> kate
==> katherine
==> keith
==> nicholas
==> nicholas_two
==> ntjy
==> paul
==> richard
==> sarah
==> sean
==> tasos
==> tom
==> yogesh
==> yongmin
current path ./database/adam. Counter = 0
current path ./database/andreea. Counter = 1
current path ./database/carla. Counter = 2
current path ./database/colin. Counter = 3
current path ./database/dan. Counter = 4
current path ./database/dennis. Counter = 5
current path ./database/derek. Counter = 6
current path ./database/derrick_nospec. Counter = 7
current path ./database/eric. Counter = 8
current path ./database/graham. Counter = 9
current path ./database/heather. Counter = 10
current path ./database/kate. Counter = 11
current path ./database/katherine. Counter = 12
current path ./database/keith. Counter = 13
current path ./database/nicholas. Counter = 14
current path ./databa

array([[178, 184, 181, ..., 200, 139, 165],
       [176, 181, 182, ..., 210, 139, 157],
       [179, 195, 180, ..., 202, 147, 169],
       ...,
       [182, 180, 179, ..., 214, 152, 167],
       [178, 177, 178, ..., 207, 153, 164],
       [188, 161, 113, ..., 210, 157, 165]], dtype=uint8)

In [4]:
#standardised dataset
data_std = StandardScaler().fit_transform(data)

/home/nicholas_sadjoli/.virtualenvs/ee4208_assign_2/local/lib/python2.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [5]:
#calculate mean face
mean = np.mean(data,axis=0)
mean_std = np.mean(data_std,axis=0)
np.savetxt("average_face_test_ii.csv", mean, delimiter=",")
cv2.imwrite("average_face_test_ii.jpg", np.array(np.reshape(mean, (100,100))) )
np.savetxt("average_face_test_ii_std.csv", mean_std, delimiter=",")
cv2.imwrite("average_face_test_ii_std.jpg", np.array(np.reshape(mean_std, (100,100))) )

True

In [6]:
mean_deduct = data - mean
mean_deduct_std = data_std - mean_std
mean_deduct.shape

(125, 10000)

In [7]:
#default_covariance
cov = mean_deduct.T.dot(mean_deduct)/(mean_deduct.shape[0] - 1)
cov_std = mean_deduct_std.T.dot(mean_deduct_std)/(mean_deduct_std.shape[0] - 1)
print cov
print cov_std
np.shape(cov)

[[2960.80645161 3072.57419355 3045.12741935 ...  685.49032258
  1697.92580645 2206.42258065]
 [3072.57419355 3402.92103226 3417.58735484 ...  672.21445161
  1765.75412903 2304.50077419]
 [3045.12741935 3417.58735484 3578.63974194 ...  657.60780645
  1795.21006452 2313.08374194]
 ...
 [ 685.49032258  672.21445161  657.60780645 ... 1145.81135484
   976.10232258 1092.25406452]
 [1697.92580645 1765.75412903 1795.21006452 ...  976.10232258
  1702.04490323 1942.27858065]
 [2206.42258065 2304.50077419 2313.08374194 ... 1092.25406452
  1942.27858065 2502.5996129 ]]
[[1.00806452 0.97579764 0.94303931 ... 0.37516998 0.76245905 0.8171021 ]
 [0.97579764 1.00806452 0.98724064 ... 0.34317345 0.73961739 0.7960559 ]
 [0.94303931 0.98724064 1.00806452 ... 0.32737065 0.73326188 0.77915705]
 ...
 [0.37516998 0.34317345 0.32737065 ... 1.00806452 0.70459832 0.65021914]
 [0.76245905 0.73961739 0.73326188 ... 0.70459832 1.00806452 0.94867762]
 [0.8171021  0.7960559  0.77915705 ... 0.65021914 0.94867762 1.008

(10000, 10000)

In [8]:
#numpy's covariance
cov_np = np.cov(mean_deduct.T)
cov_np_std = np.cov(mean_deduct_std.T)
print cov_np
print cov_np_std

[[2960.80645161 3072.57419355 3045.12741935 ...  685.49032258
  1697.92580645 2206.42258065]
 [3072.57419355 3402.92103226 3417.58735484 ...  672.21445161
  1765.75412903 2304.50077419]
 [3045.12741935 3417.58735484 3578.63974194 ...  657.60780645
  1795.21006452 2313.08374194]
 ...
 [ 685.49032258  672.21445161  657.60780645 ... 1145.81135484
   976.10232258 1092.25406452]
 [1697.92580645 1765.75412903 1795.21006452 ...  976.10232258
  1702.04490323 1942.27858065]
 [2206.42258065 2304.50077419 2313.08374194 ... 1092.25406452
  1942.27858065 2502.5996129 ]]
[[1.00806452 0.97579764 0.94303931 ... 0.37516998 0.76245905 0.8171021 ]
 [0.97579764 1.00806452 0.98724064 ... 0.34317345 0.73961739 0.7960559 ]
 [0.94303931 0.98724064 1.00806452 ... 0.32737065 0.73326188 0.77915705]
 ...
 [0.37516998 0.34317345 0.32737065 ... 1.00806452 0.70459832 0.65021914]
 [0.76245905 0.73961739 0.73326188 ... 0.70459832 1.00806452 0.94867762]
 [0.8171021  0.7960559  0.77915705 ... 0.65021914 0.94867762 1.008

In [ ]:
eig_val, eig_vect = np.linalg.eig(cov)
eig_val_std, eig_vect_std = np.linalg.eig(cov_std)
print np.shape(eig_val), np.shape(eig_vect), np.shape(eig_val_std), np.shape(eig_vect_std)

In [ ]:
for i in range(len(eig_vect)):
    print i, np.testing.assert_array_almost_equal(1.0, np.linalg.norm(eig_vect[:,i])), np.shape(eig_vect[:,i]),  np.testing.assert_array_almost_equal(1.0, np.linalg.norm(eig_vect_std[:,i])), np.shape(eig_vect_std[:,i])
print ("Every eigenvector is confirmed to have length of about 1")

In [ ]:
eigen_pairs = [(np.abs(eig_val[i]), eig_vect[:,i]) for i in range (len(eig_val))]
eigen_pairs_std = [(np.abs(eig_val_std[i]), eig_vect_std[:,i]) for i in range (len(eig_val_std))]

In [ ]:
for k in range(len(eigen_pairs)):
    print eigen_pairs[k][0], eigen_pairs_std[k][0]

In [ ]:
#note that you can specify a function as the key so that sorted() can sort based on your specified function. 
#in this case, eigen pair is sorted based on the value of the eigenvalue
eigen_pair_sorted = sorted(eigen_pairs, key=lambda pair:pair[0])
eigen_pair_sorted_std =  sorted(eigen_pairs_std, key=lambda pair:pair[0])
print eigen_pair_sorted[0], eigen_pair_sorted[9999], eigen_pair_sorted_std[0], eigen_pair_sorted_std[9999]

In [ ]:
eigen_pair_sorted.reverse()
eigen_pair_sorted_std.reverse()
print eigen_pair_sorted[0], eigen_pair_sorted[9999], eigen_pair_sorted_std[0], eigen_pair_sorted_std[9999]

In [ ]:
for count, pair in enumerate(eigen_pair_sorted):
    print count, pair[0]
for count, pair in enumerate(eigen_pair_sorted_std):
    print count, pair[0]

In [ ]:
temp = []
temp_std = []
counter = 0
counter_std = 0
for pair in eigen_pair_sorted:
    if counter == 125:
        break
    temp.append(np.real(pair[1]))
    counter += 1
    
for pair_std in eigen_pair_sorted_std:
    if counter_std == 125:
        break
    temp_std.append(np.real(pair_std[1]))
    counter_std += 1
    
eig_vect_sorted = np.array(temp).T
eig_vect_sorted_std = np.array(temp_std).T
print eig_vect_sorted, np.shape(eig_vect_sorted), 
print eig_vect_sorted_std, np.shape(eig_vect_sorted_std)
np.savetxt("eigenvector_nptest.csv", eig_vect_sorted, delimiter=",")
np.savetxt("eigenvector_nptest_std.csv", eig_vect_sorted_std, delimiter=",")

In [ ]:
eig_vect_scaled = np.copy(eig_vect_sorted) * 255
np.savetxt("eigenvector_nptest_scaled.csv", eig_vect_scaled, delimiter=",")
eig_vect_normalized = np.copy(eig_vect_sorted)
for i in range(0,10000):
    eig_vect_normalized[i] = eig_vect_normalized[i] / np.linalg.norm(eig_vect_normalized[i])
np.savetxt("eigenvector_nptest_normalized.csv", eig_vect_normalized, delimiter=",")
eig_vect_normalized_scaled = np.copy(eig_vect_normalized) * 255
np.savetxt("eigenvector_nptest_normalized_scaled.csv", eig_vect_normalized_scaled, delimiter=",")

In [ ]:
for j in range(0,10):
    cv2.imwrite("eigenfaces_test_"+str(j)+".jpg", np.reshape(eig_vect_sorted[:,j], (100,100)) )
    cv2.imwrite("eigenfaces_test_std_"+str(j)+".jpg", np.reshape(eig_vect_sorted_std[:,j], (100,100)) )
    cv2.imwrite("eigenfaces_test_scaled_"+str(j)+".jpg", np.reshape(eig_vect_scaled[:,j],(100,100)) ) 
    cv2.imwrite("eigenfaces_test_normalized_"+str(j)+".jpg", np.reshape(eig_vect_normalized[:,j], (100,100)) )
    cv2.imwrite("eigenfaces_test_normalized_scaled"+str(j)+".jpg", np.reshape(eig_vect_normalized_scaled[:,j], (100,100)) )

In [ ]:
reduced = mean_deduct.dot(eig_vect_sorted)
reduced_std = mean_deduct_std.dot(eig_vect_sorted_std)
reduced_scaled = mean_deduct.dot(eig_vect_scaled)
reduced_normalized = mean_deduct.dot(eig_vect_normalized)
reduced_normalized_scaled = mean_deduct.dot(eig_vect_normalized_scaled)
print np.shape(reduced)
np.savetxt("reduced_test_plotlyguide.csv", reduced, delimiter=",")
np.savetxt("reduced_test_plotlyguide_std.csv", reduced_std, delimiter=",")
np.savetxt("reduced_test_plotlyguide_scaled.csv", reduced_scaled, delimiter=",")
np.savetxt("reduced_test_plotlyguide_norm.csv", reduced_normalized, delimiter=",")
np.savetxt("reduced_test_plotlyguide_norm_scaled.csv", reduced_normalized_scaled, delimiter=",")